opendistro-es:
  enabled: true

  kibana:
    enabled: true
    image: amazon/opendistro-for-elasticsearch-kibana
    imageTag: 1.3.0

    config:
      server.name: kibana
      server.host: "0"

      elasticsearch.hosts: https://opendistro-opendistro-es-client-service:9200
      elasticsearch.requestTimeout: 360000

      logging.verbose: true

      # Kibana TLS Config
      server.ssl.enabled: true
      server.ssl.key: /usr/share/kibana/certs/kibana-key.pem
      server.ssl.certificate: /usr/share/kibana/certs/kibana-crt.pem

      opendistro_security.cookie.secure: true
      opendistro_security.cookie.password: ${COOKIE_PASS}

      elasticsearch.username: ${ELASTICSEARCH_USERNAME}
      elasticsearch.password: ${ELASTICSEARCH_PASSWORD}

      opendistro_security.allow_client_certificates: true
      elasticsearch.ssl.certificate: /usr/share/kibana/certs/elk-rest-crt.pem
      elasticsearch.ssl.key: /usr/share/kibana/certs/elk-rest-key.pem
      elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/certs/elk-rest-root-ca.pem"]

      # Multitenancy with global/private tenants disabled,
      # set to both to true if you want them to be available.
      opendistro_security.multitenancy.enabled: false
      opendistro_security.multitenancy.tenants.enable_private: false
      opendistro_security.multitenancy.tenants.enable_global: false
      opendistro_security.readonly_mode.roles: ["kibana_read_only"]
      elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

    ssl:
      kibana:
        enabled: true
        existingCertSecret: elasticsearch-kibana-certs
      elasticsearch:
        enabled: true
        existingCertSecret: elasticsearch-rest-certs

    elasticsearchAccount:
      secret: kibana-auth

  elasticsearch:
    master:
      enabled: true
      replicas: 3
      storageClassName: gp2
      storage: 50Gi

    initContainer:
      image: busybox
      imageTag: 1.31.0

    data:
      enabled: true
      replicas: 3
      storageClassName: gp2
      storage: 100Gi

    client:
      enabled: true
      ingress:
        enabled: false

    ssl:
      transport:
        enabled: true
        existingCertSecret: elasticsearch-transport-certs
      rest:
        enabled: true
        existingCertSecret: elasticsearch-rest-certs
      admin:
        enabled: true
        existingCertSecret: elasticsearch-admin-certs

    config:
      # Majority of options described here: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/elasticsearch.yml.example
      opendistro_security.audit.ignore_users: ["admin"]
      opendistro_security.allow_unsafe_democertificates: false
      # Set to false if running securityadmin.sh manually following deployment
      opendistro_security.allow_default_init_securityindex: true
      # See: https://opendistro.github.io/for-elasticsearch-docs/docs/security-audit-logs/
      opendistro_security.audit.type: internal_elasticsearch
      # See: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/elasticsearch.yml.example#L27
      opendistro_security.roles_mapping_resolution: BOTH
      opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]

      node:
        max_local_storage_nodes: 1
        attr.box_type: hot

      # See: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/elasticsearch.yml.example#L17
      opendistro_security.nodes_dn:
        - "CN=*,OU=Apps,O=Giant Swarm,L=Default City,C=Gs"

      processors: ${PROCESSORS:1}

      thread_pool.write.queue_size: 800

      http:
        compression: true

      # TLS Configuration Transport Layer
      opendistro_security.ssl.transport.pemcert_filepath: elk-transport-crt.pem
      opendistro_security.ssl.transport.pemkey_filepath: elk-transport-key.pem
      opendistro_security.ssl.transport.pemtrustedcas_filepath: elk-transport-root-ca.pem

      # TLS Configuration REST Layer
      opendistro_security.ssl.http.enabled: true
      opendistro_security.ssl.http.pemcert_filepath: elk-rest-crt.pem
      opendistro_security.ssl.http.pemkey_filepath: elk-rest-key.pem
      opendistro_security.ssl.http.pemtrustedcas_filepath: elk-rest-root-ca.pem
      opendistro_security.ssl.transport.truststore_filepath: opendistro-es.truststore

      # See: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/elasticsearch.yml.example#L23
      opendistro_security.authcz.admin_dn:
        - CN=admin,OU=Apps,O=Giant Swarm,L=Default City,C=Gs

    image: amazon/opendistro-for-elasticsearch
    imageTag: 1.3.0