checks:
  addAllBuiltIn: true
  exclude:
  - "default-service-account"
  - "drop-net-raw-capability"
  - "no-anti-affinity"
  - "no-liveness-probe"
  - "no-read-only-root-fs"
  - "no-readiness-probe"
  - "non-existent-service-account"
  - "required-annotation-email"
  - "required-label-owner"
  - "run-as-non-root"
  - "unset-cpu-requirements"
  - "unset-memory-requirements"
  - "writable-host-mount"
