opendistro-es:
  kibana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      path: /
      hosts:
        - kibana.x5xg2.k8s.ghost.westeurope.azure.gigantic.io
      tls:
       - secretName: kibana-tls
         hosts:
           - kibana.x5xg2.k8s.ghost.westeurope.azure.gigantic.io