version: 2.1
orbs:
  architect: giantswarm/architect@0.4.3

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push elastic-stack-app chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "elastic-stack-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
