version: 2.1
orbs:
  architect: giantswarm/architect@dev:bump-app-build-suite-version

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push efk-stack-app chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "efk-stack-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-abs:
          resource_class: 2xlarge
          name: execute chart tests
          chart_dir: "./helm/efk-stack-app"
          app-build-suite_version: "0.1.5-8917af43e56804f7b7abb4f7ba6a5a845373eb51"
          filters:
            tags:
              only: /^v.*/
