version: 2.1
orbs:
  architect: giantswarm/architect@4.7.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: package and push efk-stack-app chart
          chart: efk-stack-app
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          executor: app-build-suite
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
      # Require manual approval for running tests.
      - hold-tests:
          name: hold app tests
          type: approval
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - master
            tags:
              ignore: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          requires:
            - hold app tests
            - package and push efk-stack-app chart
          resource_class: 2xlarge
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - master
            tags:
              ignore: /^v.*/
