opendistro-certs:
  enabled: true
  organization: Giant Swarm
  expiration: 5 years

elasticsearch-curator:
  enabled: true
  configMaps:
    # Delete indices older than 7 days
    action_file_yml: |-
      ---
      actions:
        1:
          action: delete_indices
          description: "Clean up ES by deleting old indices"
          options:
            timeout_override:
            continue_if_exception: False
            disable_action: False
            ignore_empty_list: True
          filters:
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 3
            field:
            stats_result:
            epoch:
            exclude: False
    # Having config_yaml WILL override the other config
    config_yml: |-
      ---
      client:
        hosts:
          - opendistro-opendistro-es-client-service
        port: 9200
        http_auth: admin:admin

elasticsearch-exporter:
  enabled: true
  service:
    annotations:
      giantswarm.io/monitoring: "true"
      giantswarm.io/monitoring-path: /metrics
      giantswarm.io/monitoring-port: "9108"
  es:
    uri: http://admin:admin@opendistro-opendistro-es-client-service:9200
  
fluentd:
  enabled: true
  elasticsearch:
    host: opendistro-opendistro-es-client-service
    sslVerify: false
    scheme: "http"
    auth:
      enabled: true
      user: "admin"
      password: "admin"
    logLevel: "debug"

opendistro-es:
  enabled: true

  kibana:
    enabled: true
    image: quay.io/giantswarm/opendistro-for-elasticsearch-kibana
    imageTag: 1.3.0

    config:
      server.name: kibana
      server.host: "0"

      elasticsearch.hosts: http://opendistro-opendistro-es-client-service:9200
      elasticsearch.requestTimeout: 360000

      logging.verbose: false

      opendistro_security.cookie.secure: true
      opendistro_security.cookie.password: ${COOKIE_PASS}

      elasticsearch.username: ${ELASTICSEARCH_USERNAME}
      elasticsearch.password: ${ELASTICSEARCH_PASSWORD}

      # Multitenancy with global/private tenants disabled,
      # set to both to true if you want them to be available.
      opendistro_security.multitenancy.enabled: false
      opendistro_security.multitenancy.tenants.enable_private: false
      opendistro_security.multitenancy.tenants.enable_global: false
      opendistro_security.readonly_mode.roles: ["kibana_read_only"]
      elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

    elasticsearchAccount:
      secret: kibana-auth

  elasticsearch:
    master:
      enabled: true
      replicas: 3
      storageClassName: default
      storage: 50Gi

    initContainer:
      image: busybox
      imageTag: 1.31.0

    data:
      enabled: true
      replicas: 3
      storageClassName: default
      storage: 100Gi

    client:
      enabled: true
      ingress:
        enabled: false

    ssl:
      transport:
        enabled: true
        existingCertSecret: opendistro-transport-certs

    securityConfig:
      enabled: true
      path: "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig"
      internalUsersSecret: "opendistro-internal-users"
      configSecret: "opendistro-security-config"

    config:
      # Majority of options described here: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/elasticsearch.yml.example
      opendistro_security.audit.ignore_users: ["admin"]
      opendistro_security.allow_unsafe_democertificates: false
      # Set to false if running securityadmin.sh manually following deployment
      opendistro_security.allow_default_init_securityindex: true
      # See: https://opendistro.github.io/for-elasticsearch-docs/docs/security-audit-logs/
      opendistro_security.audit.type: internal_elasticsearch
      # See: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/elasticsearch.yml.example#L27
      opendistro_security.roles_mapping_resolution: BOTH
      opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]

      node:
        max_local_storage_nodes: 1
        attr.box_type: hot

      # See: https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/elasticsearch.yml.example#L17
      opendistro_security.nodes_dn:
        - "*"

      processors: ${PROCESSORS:1}

      thread_pool.write.queue_size: 800

      http:
        compression: true

      # TLS Configuration Transport Layer
      opendistro_security.ssl.transport.enforce_hostname_verification: false
      opendistro_security.ssl.transport.pemcert_filepath: elk-transport-crt.pem
      opendistro_security.ssl.transport.pemkey_filepath: elk-transport-key.pem
      opendistro_security.ssl.transport.pemtrustedcas_filepath: elk-transport-root-ca.pem

    image: amazon/opendistro-for-elasticsearch
    imageTag: 1.3.0