opendistro-es:
  enabled: true

  kibana:
    enabled: true
    image: amazon/opendistro-for-elasticsearch-kibana
    imageTag: 1.3.0

  elasticsearch:
    master:
      enabled: true
      replicas: 3
      storageClassName: default
      storage: 50Gi

    initContainer:
      image: busybox
      imageTag: 1.31.0

    data:
      enabled: true
      replicas: 3
      storageClassName: default
      storage: 100Gi

    client:
      enabled: true
      ingress:
        enabled: false

    ssl:
      transport:
        enabled: false
        existingCertSecret:
      rest:
        enabled: false
        existingCertSecret:
      admin:
        enabled: false
        existingCertSecret:

    config: {}

    image: amazon/opendistro-for-elasticsearch
    imageTag: 1.3.0