apiVersion: v1
kind: Secret
metadata:
  name: kibana-auth
  namespace: {{ .Release.Namespace }}
data:
  cookie: YWtyanA0NWRwbHVpeDZ2bGJiaXZkdjNlMHcwM2ZraWNocDI5bGxrcg==
  password: YWRtaW4=
  username: YWRtaW4=