## TODO change copyrights

# Copyright 2019 Giant, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

apiVersion: v1
# Opensearch
appVersion: 2.0.1
description: 'Opensearch'
engine: gotpl
kubeVersion: ^1.10.0-0
maintainers:
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/efk-stack-app
name: opensearch
sources:
- https://github.com/opensearch-project/helm-charts/tree/main/charts
version: 1.0.0
